# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in deep_cover.gemspec
gemspec

local = File.expand_path('Gemfile.local', __dir__)
eval_gemfile local if File.exist?(local)
